image: KananM10/imgdev
pipelines:
  default:
    - step:
        name: building
        script: 
        - cd final
        - mkdir BuildCI
        - cd BuildCI
        - cmake ..
        - cmake --build . --target test_pract1
        artifacts:
        - BuildCI/**
    - step:
        name: testing
        script: 
        - cd final/BuildCI
        - ctest -V
