name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Packages'
      run: sudo apt update && sudo apt install libcunit1-dev gcovr
    - name: 'Compile'
      run: |
        cd ./final_version/makeFile
        make
        ./bin/gameOfLife
    - name: 'Testing'
      run: |
        cd ./final_version/makeFile
        ./bin/ctest
