name: 'CI'

on:
  push:
    branches: 
    - master 

jobs:
  all_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Packages'
      run: sudo apt update && sudo apt install libcunit1-dev gcovr && sudo apt-get install libsdl2-dev
    - name: 'Compile'
      run: |
        mkdir BuildCI
        cd BuildCI
        cmake ..
        cmake --build .
    - name: 'Testing'
      run: |
        cd BuildCI
        chmod +x *
        ctest -V
